export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header style={{ color: "Gray" }}>Header</header>
      <body>{children}</body>
      <footer>Footer</footer>
    </html>
  );
}
